calendar_plus.settings:
  type: config_object
  label: 'Calendar Plus settings'
  mapping:
    ics_storage:
      type: string
      label: 'ICS file storage method'
    email_subject:
      type: string
      label: 'Invitation email subject'
    email_body:
      type: string
      label: 'Invitation email body'
    reminder_days:
      type: integer
      label: 'Reminder days before event'
